format_version: 4
pipelines:
  build_and_package:
    group: kubernetes
    display_order: 1
    environment_variables:
      DOCKERHUB_USERNAME: shawntp
    materials:
      git:
        git: https://github.com/shawnparslow/node-bulletin-board.git
        shallow_clone: true
    stages:
    - build_stage:
        # This can be set to manual if desired
        approval:
          type: success
        jobs:
          build_image:
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: bulletin-board
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/bulletin-board
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile.application
                command: /bin/bash
    stages:
    - test_stage:
        # This can be set to manual if desired
        approval:
          type: success
        jobs:
          build_image:
            elastic_profile_id: demo-app
            tasks:
            - exec:
                arguments:
                - -c
                - docker run -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL npm test
                command: /bin/bash
