format_version: 4
pipelines:
  deploy_to_prod_two:
    group: kubernetes
    display_order: 4
    environment_variables:
      NAMESPACE: gocd
    secure_variables:
      KUBE_TOKEN: # YOUR VALUE
    materials:
      uat:
        pipeline: deploy_to_uat
        stage: approval_stage
      build:
        pipeline:  build_and_package
        stage: build_stage
      SourceCodeRepo:
        git: # YOUR VALUE
        shallow_clone: false
    stages:
    - deploy_to_cluster:
        approval:
          type: success
        jobs:
          deploy:
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_package
                stage: build_stage
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                command: ./app-deployment.sh
                arguments:
                run_if: passed