format_version: 4
pipelines:
  deploy_to_prod:
    group: kubernetes
    display_order: 3
    environment_variables:
      NAMESPACE: gocd
    secure_variables:
      KUBE_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLXFzcmg4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkZWVkOTQwYi1hZTM0LTExZTktYmQ2Ny00MjAxMGE4MDAxMTciLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YWRtaW4tdXNlciJ9.ODnv9zXXrDb3pj-faX8XWBZ-QJWqPnG_RxB4A7H_EySeHLdTzUrBmMaeLi3wXTAHjPfBmdCgD4D1v0ZtMS9lfYLDOshWocxWwuUGDK_ieRZaUdTo7ol0AQujoxunpv7jjmhtOZIIbqz32J6JMejl1vIlZkmr8_lE7TC4ArNnlsZNljDKpAkhWcgyeWtdwnUYt34doFG8bcOo1oBdLIXTu7IcYsTtsPiv1btqsz7bmEQhAJcC1DP-HV-f6QP4ZueiSRz0WGhQJpRv-tEqS6OlxZOxQm8qa5JIAxxFDk2cmHA88PW0dlW7rGVDOaZDK6jl6DTXSbVSo2nxFt1DXeJEWg
    materials:
      build:
        pipeline: build_and_package
        stage: test_stage
      SourceCodeRepo:
        git: https://github.com/shawnparslow/node-bulletin-board.git
        shallow_clone: false
    stages:
    - deploy_to_prod:
        approval:
          type: success
        jobs:
          deploy:
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_package
                stage: build_stage
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                command: ./app-deployment.sh
                arguments:
                run_if: passed
